package XMLGenerator;

public class NodeTag {
    static final String CompanyRegistrationNumber = "ssmt-dei:CompanyRegistrationNumber";
    static final String NameOfReportingEntity = "ssmt-dei:NameOfReportingEntity";
    static final String FormerNameOfCompany = "ssmt-dei:FormerNameOfCompany";
    static final String OriginOfCompany = "ssmt-dei:OriginOfCompany";
    static final String StatusOfCompany = "ssmt-dei:StatusOfCompany";
    static final String TypeOfCompany = "ssmt-dei:TypeOfCompany";
    static final String DisclosureOfFinancialStatementsPreparationForCurrentSubmission = "ssmt-dei:DisclosureOfFinancialStatementsPreparationForCurrentSubmission";
    static final String CompanyCurrentFinancialYearStartDate = "ssmt-dei:CompanyCurrentFinancialYearStartDate";
    static final String CompanyCurrentFinancialYearEndDate = "ssmt-dei:CompanyCurrentFinancialYearEndDate";
    static final String CompanyPreviousFinancialYearStartDate = "ssmt-dei:CompanyPreviousFinancialYearStartDate";
    static final String CompanyPreviousFinancialYearEndDate = "ssmt-dei:CompanyPreviousFinancialYearEndDate";
    static final String StatusOfCarryingOnBusinessDuringFinancialYear = "ssmt-dei:StatusOfCarryingOnBusinessDuringFinancialYear";
    static final String DisclosureOfFinancialStatementsAuditStatus = "ssmt-dei:DisclosureOfFinancialStatementsAuditStatus";
    static final String BasisOfAccountingStandardsAppliedToPrepareFinancialStatements = "ssmt-dei:BasisOfAccountingStandardsAppliedToPrepareFinancialStatements";
    static final String TypeOfSubmission = "ssmt-dei:TypeOfSubmission";
    static final String NatureOfFinancialStatements_MFRS = "ssmt-dei-ee-mfrs:NatureOfFinancialStatements";
    static final String NatureOfFinancialStatements_MPERS = "ssmt-dei-ee-mpers:NatureOfFinancialStatements";
    static final String DescriptionOfPresentationCurrency = "ssmt-dei:DescriptionOfPresentationCurrency";
    static final String DescriptionOfFunctionalCurrency = "ssmt-dei:DescriptionOfFunctionalCurrency";
    static final String LevelOfRoundingUsedInFinancialStatements = "ssmt-dei:LevelOfRoundingUsedInFinancialStatements";
    static final String DateOfFinancialStatementsApprovedByBoardOfDirectors = "ssmt:DateOfFinancialStatementsApprovedByBoardOfDirectors";
    static final String DateOfCirculationOfFinancialStatementsAndReportsToMembers = "ssmt:DateOfCirculationOfFinancialStatementsAndReportsToMembers";
    static final String DateOfFinancialStatementsAndReportsOfDirectorsAndAuditorsLaidInAnnualGeneralMeeting = "ssmt:DateOfFinancialStatementsAndReportsOfDirectorsAndAuditorsLaidInAnnualGeneralMeeting";
    static final String DateOfStatutoryDeclaration = "ssmt:DateOfStatutoryDeclaration";
    static final String DisclosureOnWhetherCompanysSharesAreTradedOnAnyOfficialStockExchange = "ssmt:DisclosureOnWhetherCompanysSharesAreTradedOnAnyOfficialStockExchange";
    static final String DisclosureOfRegulationAppliedDuringIncorporationOfCompany = "ssmt:DisclosureOfRegulationAppliedDuringIncorporationOfCompany";
    static final String DisclosureOfWhetherCompanyRegulatedByBankNegaraMalaysiaAtFinancialYearEnd = "ssmt:DisclosureOfWhetherCompanyRegulatedByBankNegaraMalaysiaAtFinancialYearEnd";
    static final String MSICCode = "ssmt:MSICCode";
    static final String DescriptionOfBusiness = "ssmt:DescriptionOfBusiness";
    static final String DescriptionOnWhetherCompanyHadAppliedForAnyExemptionWaiverReliefOrExtensionOfTimeWithRegardToAnnualReturnOrFinancialStatementsAndReportsFromRegistrarOrMinister = "ssmt:DescriptionOnWhetherCompanyHadAppliedForAnyExemptionWaiverReliefOrExtensionOfTimeWithRegardToAnnualReturnOrFinancialStatementsAndReportsFromRegistrarOrMinister";
    static final String MethodUsedForPreparingStatementOfFinancialPosition = "ssmt:MethodUsedForPreparingStatementOfFinancialPosition";
    static final String MethodUsedForPreparingStatementOfProfitOrLoss = "ssmt:MethodUsedForPreparingStatementOfProfitOrLoss";
    static final String MethodUsedForPreparingStatementOfComprehensiveIncome = "ssmt:MethodUsedForPreparingStatementOfComprehensiveIncome";
    static final String MethodUsedForPreparingStatementOfCashFlows = "ssmt:MethodUsedForPreparingStatementOfCashFlows";
    static final String DisclosureOnWhetherComparativePeriodValuesAreRestated = "ssmt:DisclosureOnWhetherComparativePeriodValuesAreRestated";
    static final String DisclosureOnWhetherOpeningStatementChangedDueToChangesInAccountingStandards = "ssmt:DisclosureOnWhetherOpeningStatementChangedDueToChangesInAccountingStandards";
    static final String DisclosureOnWhetherReclassificationOfPreviousFinancialStatementsChangedDueToChangesInAccountingStandards = "ssmt:DisclosureOnWhetherReclassificationOfPreviousFinancialStatementsChangedDueToChangesInAccountingStandards";
    static final String DisclosureOnWhetherCompanyChangedDurationOfFinancialReportingPeriod = "ssmt:DisclosureOnWhetherCompanyChangedDurationOfFinancialReportingPeriod";
    static final String DisclosureOfDirectorsReportExplanatory = "ssmt:DisclosureOfDirectorsReportExplanatory";
}
